export const GAME_CONFIG: any = {
  SCREEN_MARGIN: 200,
  BACKGROUND_COLOR: "#FFF",
  LEVEL_WIDTH: 5000,
  PLAYER_SIZE: 80,
  PLAYER_SPEED: 75,
  PLAYER_JUMP_STRENGTH: 25,
  PLATFORM_HEIGHT: 80,
  GRAVITY: 1,
  FRICTION: 0.9,
};
